version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - gci
    - misspell
    - unconvert
    - unparam
    - prealloc
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/madic-creates/restic-backup-operator)

exclusions:
  rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: zz_generated
      linters:
        - all
