version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - prealloc
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
      - path: zz_generated
        linters:
          - all

formatters:
  enable:
    - gofmt
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/madic-creates/restic-backup-operator)
